### ISSUE TITLE
Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by Morgy93** [scandipwa/create-magento-app#59]
### Describe the bug

After successful `npm run start` I tried to execute the `bin/magento` which throws the following error:
```
Class 'DOMDocument' not found
#0 create-magento-app/vendor/magento/framework/Config/Dom.php(116): Magento\Framework\Config\Dom->_initDom()
#1 create-magento-app/vendor/magento/framework/ObjectManager/Config/Reader/Dom.php(70): Magento\Framework\Config\Dom->__construct()
#2 create-magento-app/vendor/magento/framework/Config/Reader/Filesystem.php(151): Magento\Framework\ObjectManager\Config\Reader\Dom->_createConfigMerger()
#3 create-magento-app/vendor/magento/framework/Config/Reader/Filesystem.php(132): Magento\Framework\Config\Reader\Filesystem->_readFiles()
#4 create-magento-app/vendor/magento/framework/App/ObjectManagerFactory.php(279): Magento\Framework\Config\Reader\Filesystem->read()
#5 create-magento-app/vendor/magento/framework/App/ObjectManagerFactory.php(140): Magento\Framework\App\ObjectManagerFactory->_loadPrimaryConfig()
#6 create-magento-app/vendor/magento/framework/App/Bootstrap.php(212): Magento\Framework\App\ObjectManagerFactory->create()
#7 create-magento-app/vendor/magento/framework/App/Bootstrap.php(127): Magento\Framework\App\Bootstrap->__construct()
#8 create-magento-app/vendor/magento/framework/Console/Cli.php(184): Magento\Framework\App\Bootstrap::create()
#9 create-magento-app/vendor/magento/framework/Console/Cli.php(84): Magento\Framework\Console\Cli->initObjectManager()
#10 create-magento-app/bin/magento(22): Magento\Framework\Console\Cli->__construct()
#11 {main}
```` 

### Did you try recovering your dependencies?

Since this was the initial setup without errors, I don't expect to need any recovering action afterwards.

### Environment

WSL2 Ubuntu
Magento 2.4.3-p1

### Steps to reproduce

1. `npx create-magento-app my-app`
2. `cd my-app`
3. `npm run start`
4. `bin/magento`

### Expected behavior

No error is thrown and the command executes.

### Actual behavior

It did not execute because of missing php dependencies.

**Comment by Morgy93** [comment]
It works via `npm run cli` but I understood that you primarily work on the host where php and all is installed.
If that's NOT the case, this is not really an issue and might just need a better explanation in the docs.
